spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD:postgres}
    username: ${POSTGRES_USERNAME:postgres}
    url: jdbc:postgresql://localhost:5433/
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081
